### ISSUE TITLE
Inventory disappears after launching desktop mode

### ISSUE THREAD

**Issue by nasawhy** [jrbudda/Vivecraft_111#13]
I'm using the Oculus Rift/Touch and everything works fine in Oculus, but after playing the same saved game in desktop mode and then going back to VR mode, all my inventory is gone, chests are empty, and my wooden doors have disappeared from my house.

I have not tried to replicate this with the Vive yet, I will try it tonight and post any findings here.

**Comment by jrbudda** [comment]
This happens when you play a world in 1.7.x and then jump to a more current versions, or vice versa.

**Comment by nasawhy** [comment]
Ok, thanks! I'll try to figure out how that is happening.
