### ISSUE TITLE
Eye stencil backwards?

### ISSUE THREAD

**Issue by sideswipeBL** [jrbudda/Vivecraft_111#15]
I just got a new motherboard recently and reinstalled Vivecraft 1.11.2 to experience the new Minecraft version in VR, but once I loaded into the world, I couldn't see anything. This is what it looks like on the desktop:
[![somethingswrong.png](https://s23.postimg.org/51mwpe4tn/somethingswrong.png)](https://postimg.org/image/7679qh6g7/)
Yeah, the entire field of view was black. I cannot change any settings.
Is this because of the version? Is 1.11.2 broken, since it's listed as "just testing"?

**Comment by jrbudda** [comment]
Uhh the eye stencil is... Backwards? Wow. That's new. Turn off eye stencil in stereo rendering settings.


-----Original Message-----

**Comment by sideswipeBL** [comment]
How do I do that? Sorry, I haven't used Vivecraft in a while.

**Comment by jrbudda** [comment]
vr settiings > stereo rendering

**Comment by sideswipeBL** [comment]
Oh, yeah I didn't realize I could change settings in the main menu. I'll try turning that off now.

**Comment by jrbudda** [comment]
this might be fixed in the latest update.
