### ISSUE TITLE
Requests and issues

### ISSUE THREAD

**Issue by Aesop112** [jrbudda/Vivecraft_111#19]
Issues

Walking up blocks doesn't work. Instead it jumps up blocks.

Cannot teleport onto fences.

You can poke your head and arm through a protected door and teleport into a locked door that way.

Boat rowing turning can go from non responsive to overturning too much. 

Feature request:

Amount Trigger is squeezed will determine walking speed. 

A third person view of your character show on the display mirror. Maybe the mixed reality cam could be reworked? 

A little down facing indicator arrow over enemies head when they're within room scale attack range.

Integrated proximity chat for all!

NoCubes mod support. That'd be the talk of town right there.

The ability to scale some of the gui elements like the inventory menu, and offset the wrist and arm hotbars as currently if you have the hot ar set to wrist it gets in the way when knocking an arrow to your bow.

**Comment by Thk54** [comment]
Would it be possible to implement the "intense" control scheme from the win ten edition? (primarily the ability to use oculus touch thumbstick to move in directions i'm not facing)

**Comment by jrbudda** [comment]
devoting the whole thumbstick to movement would starve us of buttons too much I think. Tho I haven't looked at their control scheme

**Comment by Thk54** [comment]
have you looked at it or have any plans to do so?

**Comment by jrbudda** [comment]
Ok in the spirit of closing out this issue

> Walking up blocks doesn't work. Instead it jumps up blocks.

 This is on the TODO

> Cannot teleport onto fences.

I think I fixed this.

> You can poke your head and arm through a protected door and teleport into a locked door that way.

I can't really fix this as you'll always be able to go places within your room, teleporting is always going to be cheaty.

 > Boat rowing turning can go from non responsive to overturning too much.

I've just updated this for the forthcoming 1.12.2v5

 > Amount Trigger is squeezed will determine walking speed.

Techjar is working on an overhaul of the input system and this should be possible when that is done.

 > A third person view of your character show on the display mirror. Maybe the mixed reality cam could be reworked?

On the TODO.

> A little down facing indicator arrow over enemies head when they're within room scale attack range.

Don't really see this one happening, roomscale attack range is determined by where your arm is, not where you're standing... and I don't really want to dig into or modify mob rendering for mod compatibility reasons.

> Integrated proximity chat for all!

Still on the TODO, I'm hoping I can get into the Discord in-game beta program.

> NoCubes mod support. That'd be the talk of town right there.

Not gonna happen. 

> The ability to scale some of the gui elements like the inventory menu, and offset the wrist and arm hotbars as currently if you have the hot ar set to wrist it gets in the way when knocking an arrow to your bow.

Reworked some gui code for the next release. Custom GUI/HUD scaling will be added in the near future.

>Would it be possible to implement the "intense" control scheme from the win ten edition? (primarily the ability to use oculus touch thumbstick to move in directions i'm not facing, though i'm not 100% sure how the vive's dpad looking thing works but even if it only provides dpad input still would i think be nice to have as an option)

This was done.
