### ISSUE TITLE
Add an option to reverse boat controls.

### ISSUE THREAD

**Issue by destrofer** [jrbudda/Vivecraft_111#23]
Since rowing is only possible forward it becomes very awkward when turning. You have to row with the left arm to turn left, while in reality if you row forward with the left arm you would turn right.

It would be great to have an option allowing to reverse the boat tunrning controls. And if possible for those controls to be according to reality by default :)

**Comment by jrbudda** [comment]
its a rowboat, you're technically sitting in it backwards.

**Comment by destrofer** [comment]
Well ... technically you can row forward (at least on some boats). It's just more exhausting since different less developed muscles are used. But yeah, you're right, that was my mistake. I started rowing the boat as is after entering it, without turning around and didn't notice that moving left arm moves the "right" oar.

You could still make that option for those who want it to be reversed. But it is up to you. At least there are no more complaints from my side :)
