### ISSUE TITLE
Cannot land on lilly pad

### ISSUE THREAD

**Issue by destrofer** [jrbudda/Vivecraft_111#24]
The teleportation arc goes right through the lilly pad.

**Comment by jrbudda** [comment]
Try this, it also has an update pumpkin-face thing

[vivecraft-1.11.2-jrbudda-4Rr4-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/709456/vivecraft-1.11.2-jrbudda-4Rr4-installer.exe.zip)

**Comment by destrofer** [comment]
Yeah, this does the trick. Btw ... HUGE thanks for the great VR minecraft experience! :)
