### ISSUE TITLE
[NVIDIA 378.49] Vivecraft crashes on start

### ISSUE THREAD

**Issue by YmiYugy** [jrbudda/Vivecraft_111#25]
I can't start the game.
http://pastebin.com/q1Uang0v

**Comment by Danondso** [comment]
By chance are you using a Nvidia graphics card?

**Comment by YmiYugy** [comment]
yes, I do

**Comment by Danondso** [comment]
The latest driver version (378.49) causes Vivecraft to crash at the moment.
Your pastebin looked similar to mine when I tried to run Vivecraft with the
latest driver. Is that the driver version you're running?

**Comment by YmiYugy** [comment]
Sadly that it the version I am using. Is there a workaround or do I need to role the driver back?

**Comment by Danondso** [comment]
Installing the previous driver version should fix it. I did that and it
worked just fine.

**Comment by YmiYugy** [comment]
Thank you. It worked

**Comment by gene357** [comment]
Nvidia has release a hot fix. This did resolve the issue for me.
https://forums.geforce.com/default/topic/991248/geforce-drivers/announcing-geforce-hotfix-driver-378-57/

**Comment by jrbudda** [comment]
excellent, thank you
