### ISSUE TITLE
crash with new Minecraft Launcher and custom --workDir

### ISSUE THREAD

**Issue by fayer3** [jrbudda/Vivecraft_111#27]
When using the new Minecraft Native Launcher and changing the --workDir to something else than the Default I get the following crash: https://gist.github.com/fayer3/2252c497c561bc4cfe9448e3601a70a8
looks like it's always looking for the openvr_api.dll in %APPDATA% .minecraft folder

**Comment by fayer3** [comment]
Still happening wit 9r1. only way to play is copying the win32/win64 folders from the selected installation folder into %APPDATA%\.minecraft

**Comment by Techjar** [comment]
Yeah, I'll go ahead and fix that.

**Comment by jrbudda** [comment]
this r fixed.
