### ISSUE TITLE
Crash on load/starting (Mojang Screen)

### ISSUE THREAD

**Issue by HorizonCode** [jrbudda/Vivecraft_111#28]
first off, i use an emulated vr headset (samsung galaxy s5 with vr box 2) with an streaming program called riftcat.
i updated my gpu driver too.

when i start vivecraft 1.11.2, it crashes with this code:
`Process closed with exit code -1073740791`

**Comment by jrbudda** [comment]
if you have the very latest NVIDIA driver it causes a crash. Either roll back or look for the hotfix.

**Comment by HorizonCode** [comment]
:/

**Comment by HorizonCode** [comment]
where can i download the previous? GTX 750 TI OC

**Comment by HorizonCode** [comment]
okay its working, thanks, is there a way to change the walk type in singeplayer?

**Comment by jrbudda** [comment]
yes, locomotion options.

**Comment by HorizonCode** [comment]
thanks <3
