### ISSUE TITLE
Companion mod Linux release

### ISSUE THREAD

**Issue by Xodetaetl** [jrbudda/Vivecraft_111#29]
A .jar release for the companion mod would be warmly welcomed!

**Comment by Xodetaetl** [comment]
Mmh, the .exe is actually a .jar

**Comment by jrbudda** [comment]
does it work?

**Comment by Xodetaetl** [comment]
It installed but I couldn't test it myself as I'm the one with the Vive. I'll let you know when one of the players on my server has tried it.
