### ISSUE TITLE
Fishing Line Misaligned

### ISSUE THREAD

**Issue by Shadaez** [jrbudda/Vivecraft_111#3]
On other players as well as yourself, can provide a screenshot if helpful.

**Comment by jrbudda** [comment]
ummm not seein that on my end, looks normal to me

**Comment by Shadaez** [comment]
sorry for not responding I was busy, still happening for me

heres a screen:
http://i.imgur.com/XxqA8Ko.png

**Comment by jrbudda** [comment]
oh you're in seated mode. yea that's a thing.
