### ISSUE TITLE
Vivecraft 1.11.2 v7r1 Chat closes right after opening.

### ISSUE THREAD

**Issue by THEHCKEABLE** [jrbudda/Vivecraft_111#31]
Whenever you try to open chat via the key it is bound to, or via the start menu it will automatically close. Pressing the command key will do they same. It seems to occur in both seated and standing modes.

**Comment by Mickyelloow** [comment]
I have the same problem, but only in seated mode. Standing is fine

**Comment by jrbudda** [comment]
ah sorry we have this fixed for the next release. Here's a pre-release.
[vivecraft-1.11.2-jrbudda-8pre-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/829501/vivecraft-1.11.2-jrbudda-8pre-installer.exe.zip)
