### ISSUE TITLE
Cannot Swing or attack without an entity or block in range.

### ISSUE THREAD

**Issue by THEHCKEABLE** [jrbudda/Vivecraft_111#32]
Not sure if this is a bug, but it would be quite useful if there was a way to enable being able to "Attack" without something in range. Plugins like "Magic" cannot be used except on block or entities that are very close, rendering ranged spells useless. I imagine some other plugins could face similar issues, though I haven't tried any beyond this.

**Comment by jrbudda** [comment]
this is done.
