### ISSUE TITLE
Climbing ladders stopped working in 8pre

### ISSUE THREAD

**Issue by ochilan** [jrbudda/Vivecraft_111#36]
I can no longer climb ladders in teleport mode despite Simulate Falling set to On. It works as expected when downgrading to 7r1.

You can actually see the moment I discovered the problem in one of my latest videos (pretty much right at the beginning): https://www.youtube.com/watch?v=28T0FbjLaLI

**Comment by jrbudda** [comment]
thanks i will take a look

**Comment by jrbudda** [comment]
Give this build a try, this should fix both the falling after teleporting onto the ladder, and not being able to 'roomscale climb'. This does require a change in that when you roomscale climb ladders in teleport mode you will not fall at all so long as you are on the ladder.

[vivecraft-1.11.2-jrbudda-8-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/852873/vivecraft-1.11.2-jrbudda-8-installer.exe.zip)

**Comment by ochilan** [comment]
Thank you for the quick reply, that build seems to work :) Hm, I got a bit used to descending quickly by "falling" down the ladder, but on the other hand being able to hold on the ladder is very nice as well. And indeed, it was always a weird feeling to suddenly slide down.

Would it be possible to climb down by holding the Sneak button (i.e. left side buttons by default)? But if this just complicates things it's not that important to me.

**Comment by jrbudda** [comment]
Actually the vanilla behavior of the sneak button is to stop you from falling at all on ladders. It's now working like it used to, back before I added in the roomscale climbing. I think it's a good compromise.

**Comment by ochilan** [comment]
That's true, that would reverse the original logic. Or maybe make it an option whether holding or not holding the side buttons lets the player slide down a ladder. The idea would just be to enable sliding down a (long) ladder quickly, if so desired. But if you think that's not necessary or makes things ugly internally, then that's fine as well.

**Comment by ochilan** [comment]
Not sure whether I should open a new bug for this: Climbing ladders again (or still?) doesn't work for me in version 9r1. It worked in the build you gave me, and I think I haven't tried another version until 9r1.

**Comment by jrbudda** [comment]
I have no idea how my fix could have gone away, fixed this right before starting the Forge integration, will look into it.

**Comment by jrbudda** [comment]
Should sort it, again. Dunno where my fixes went but they were in 8's commit and then got deleted :(.

Still need to look into your issue with exiting The End.

[vivecraft-1.11.2-jrbudda-9r3-installer.zip](https://github.com/jrbudda/Vivecraft_111/files/1003456/vivecraft-1.11.2-jrbudda-9r3-installer.zip)

**Comment by ochilan** [comment]
Tried 9r3 and ladders seem to be working again, thanks. ^^
