### ISSUE TITLE
no keyboard when making a sign

### ISSUE THREAD

**Issue by fpga68k** [jrbudda/Vivecraft_111#38]
When placing a sign there is no keyboard coming up to enter the text. Maybe I just missed how to open the onscreen keyboard. It would be helpful if it would just appear when a sign is placed somewhere.

**Comment by jrbudda** [comment]
The keyboard should indeed come up when you open the sign editor or chat. You can use the left grip+left appmenu combo to open the keyboard at any time. If it won't open with that... maybe there's something wrong with steamvr and try restarting that.

**Comment by Techjar** [comment]
This should be fixed in the next release, whenever that happens.
