### ISSUE TITLE
Feature request for plugin

### ISSUE THREAD

**Issue by AireagoirSteam** [jrbudda/Vivecraft_111#40]
I was wondering if porting the plugin to sponge or making a forge 1.11.2 of the mod would be possible.
since if succesfully ported to sponge then mods or just the plugin could be used with sponge vanilla or sponge forge.

Since as far as I'm aware from my limited knowledge of how Minecraft loads using mod with the current version is impossible.

**Comment by Nuchaz** [comment]
I am also curious if there might be plans for a forge compatible version for 1.11.2. I just got a chance to try Vivecraft and I am blown away. I would love to be able to use forge mods with it on MC 1.11.2.

**Comment by jrbudda** [comment]
Forge for 1.11.2 is now out.
