### ISSUE TITLE
(Request) make touchpad buttons assignable in a cross shape

### ISSUE THREAD

**Issue by fayer3** [jrbudda/Vivecraft_111#45]
Currently the touchpad buttons are only assignable in a diagonal way:
![diagonal](https://cloud.githubusercontent.com/assets/8282299/25584528/b99a6b24-2e96-11e7-8440-6e76ebe1d865.png)

It would be nice if the would also be assignable in a cross shape:
![cross](https://cloud.githubusercontent.com/assets/8282299/25584533/bdfea43c-2e96-11e7-91aa-ce5d80f6fd77.png)

this would make it possible to assign the touchpad buttons for walking without it feeling awkward.

**Comment by jrbudda** [comment]
Actually if I were to do walking on the touchpad I'd do it Onward style where you just touch it and it uses the actual direction.  I'll think about the cross-style buttons.

**Comment by Techjar** [comment]
I could do the cross implementation pretty easily when I rewrite the input code.
