### ISSUE TITLE
Infoboxes cut off

### ISSUE THREAD

**Issue by fayer3** [jrbudda/Vivecraft_111#47]
when above a tab from the creative inventory the infobox cut off if there is no background:
![screenshot_sat_may_06_23-45-04_2017](https://cloud.githubusercontent.com/assets/8282299/25776287/ace5098e-32ba-11e7-97fb-4c420b377cdd.png)
this does not affect the infoboxes of blocks:
![screenshot_sat_may_06_23-45-09_2017](https://cloud.githubusercontent.com/assets/8282299/25776293/beb57270-32ba-11e7-88dd-71e2fc69b928.png)
this was tested with version 9r1, without forge.

this also affects mod overlays like the JEI GUI when playing with forge:
![screenshot_sat_may_06_23-59-36_2017](https://cloud.githubusercontent.com/assets/8282299/25776297/d96d7b1c-32ba-11e7-9133-51780fde1d66.png)

**Comment by Techjar** [comment]
These alpha blending issues are really hard to fix. In the meantime, if it bothers you, turning on the menu background should fix it.

**Comment by fayer3** [comment]
thanks will do that.

**Comment by Techjar** [comment]
Are you still having this issue on the latest release (10pre)? I'm not able to reproduce it.

**Comment by fayer3** [comment]
Just tested with 10pre10. Looks like it's fixed.

**Comment by Techjar** [comment]
Ok cool. I'm not sure when or how it got fixed, but I'll take it.
