### ISSUE TITLE
Exiting the End kills the player

### ISSUE THREAD

**Issue by ochilan** [jrbudda/Vivecraft_111#48]
Hello,

I can reproduce this issue reliably, have tried multiple times. Does not happen in non-VR mode with the same world. In VR, exiting the End through the center portal always makes me fall off the world and die.

I have made a short video showing the issue: https://youtu.be/AIpVnKITZmI (I have also tried without moving the bed right before going into the End, but this made no difference – note that I did sleep before entering the End).

In fact I will release a key episode of my Let's Play very soon where you can also see this issue at the end... in the End. You can imagine how much joy this brought me after an hour of fighting and having obtained 65 XP levels ;) ... Well, not so bad, I can get these back another way, but anyway... BAD TIMING!

Let me know if you wish to have my world for debugging purposes where I'm readily standing in front of the bed next to the (entering) portal.

Vivecraft version 9r2.

**Comment by Techjar** [comment]
It's supposed to play the credits, something must be spewing an exception and cancelling the whole portal function. Can you give me the latest.log and fml-client-latest.log (if running Forge) after reproducing this issue?

**Comment by ochilan** [comment]
I saw the moment when it was supposed to play the credits after exiting the first time. It was like standing in the VR main menu, but without the menu actually showing. After pushing some button I was falling as shown in the video. The video obviously doesn't show the first time I was existing the End, so I guess it's not supposed to play the credits in this case. Anyway, the result is the same.

Will check for the log you mentioned right away.

**Comment by Techjar** [comment]
It should always play the credits when you exit the end.

**Comment by ochilan** [comment]
Hm okay, I see. What I can say is that I only got to the "main menu" scene after exiting it the first time. I also didn't get the credits in non-VR mode, but safely returned to the regular world

Anyway, I'm attaching the latest.log. No Forge installed, at least it shouldn't be.

[latest.log.txt](https://github.com/jrbudda/Vivecraft_111/files/993878/latest.log.txt)

**Comment by Techjar** [comment]
Can you remove the bed and see what happens?

**Comment by ochilan** [comment]
Sure thing. The result is the same, just without the "bed was obstructed" message.

**Comment by Techjar** [comment]
Huh. I will test this later to see if I can reproduce it.

**Comment by jrbudda** [comment]
What a fantastic way to celebrate 100 episodes :)

**Comment by Techjar** [comment]
...what?

**Comment by ochilan** [comment]
Thanks :) By the way, I have tried a fresh portal in a creative world and was able to reproduce the issue there as well.
