### ISSUE TITLE
Possible Update To Forge 2296?

### ISSUE THREAD

**Issue by Darkosto** [jrbudda/Vivecraft_111#49]
Hey JrBudda!

Thanks for all your hard work on vicecraft! Would it be possible for a vivecraft release along with 2296 forge? I wanted to hop on the forgecraft server and test some new mods in VR, but Buildcraft specifically requires the latest version of Forge.

I appreciate everyone you do!
Darkosto

**Comment by Techjar** [comment]
Yes, will do it when we update Optifine.

**Comment by Darkosto** [comment]
Thank you!

**Comment by jrbudda** [comment]
I don't think this will get done before the release of 1.12, and we may not update 1.11.2 after that. What you can do tho, is change the Forge version in the profile .json file and install that version and that might/should work.
