### ISSUE TITLE
Does not display on VR headset

### ISSUE THREAD

**Issue by Karloalvaro7** [jrbudda/Vivecraft_111#5]
Just installed 1.11 vivecraft. When I launch it, I can see everything through the mirrored display on my desktop, but not on my VR headset (which only shows the SteamVR lobby).

**Comment by jrbudda** [comment]
A couple things can cause this. One solution is here http://www.vivecraft.org/faq/.

**Comment by Karloalvaro7** [comment]
That worked! Sorry I didn't see it on the FAQ first. Thanks!

**Comment by Caffa** [comment]
I have the same issue but I can't open the NVIDIA control panel since it says I am not running a monitor connected to NVIDIA GPU...

**Comment by drewc5131** [comment]
^^^

**Comment by NuclearBlade410** [comment]
I have a pc and I have did not download the non vr or the other problems and its still not working.

**Comment by Techjar** [comment]
http://www.vivecraft.org/faq/#gpu

**Comment by NuclearBlade410** [comment]
I have none of those problems I don't have an intel GPU and my hmd and moniter are plugged in to the gpu

**Comment by Techjar** [comment]
Then your problem must be something else. Come to the Discord server where we can help you more easily.

**Comment by NuclearBlade410** [comment]
so whats the code?

**Comment by Techjar** [comment]
The link is on the website.

**Comment by NuclearBlade410** [comment]
ok I'm in thanks
