### ISSUE TITLE
[Forge-NonVR Companion] - [Mod Support] Joypad for 1.11.2

### ISSUE THREAD

**Issue by IVIrEos** [jrbudda/Vivecraft_111#50]
It's a mod that adds Xbox controller support to the game along with some on screen prompts to match + split screen, etc.

When trying to move around with the left thumbstick if you do any combination of 2 different directions (diagonal directions) the initial direction gets stuck requiring the user to press in that direction again to stop it.

If you press left then rotate it up, if you let go of the thumbstick it continues to travel left.

I tried the mod with regular minecraft w/ forge and the issue is non existent there.

**Comment by jrbudda** [comment]
Could you pastebin a fml-client-latest.log? Given the minimal modifications the non-vr client makes this almost has to be an ASM failure.

**Comment by IVIrEos** [comment]
Nevermind, I didn't realize it at first but this problem is specific to running a Spigot Server.  Which I think has nothing to do with you.  Go ahead and close this issue at your leisure.

**Comment by jrbudda** [comment]
oh so you're using the nonvr client with forge and playing on a spigot server. Odd that that interferes with control... does it work right when played on a Forge server? does the joypad mod have a server-side component?

**Comment by IVIrEos** [comment]
I have not tried setting up a forge server yet.  Will have to do a bit a googling on that and get back to ya.

**Comment by jrbudda** [comment]
yea im just wondering if its a spigot issue or a multiplayer issue in general. Also this is interesting in the log: 
Failed putting value in keyBufferField java.nio.BufferOverflowException

this log file is from vanilla minecraft with forge, right?

**Comment by IVIrEos** [comment]
That was actually vanilla minecraft w forge running on the spigot server was the last profile I loaded in.

**Comment by jrbudda** [comment]
Honestly it might be a bug in Forge.

**Comment by IVIrEos** [comment]
I loaded up forge server.  Problem does not exist.  It's a Spigot + Joypad problem.
