### ISSUE TITLE
[CRASH BUG] - [Vivecraft Forge 1.11.2]  Crashes when opening inventory in Creative Mode 

### ISSUE THREAD

**Issue by IVIrEos** [jrbudda/Vivecraft_111#52]
Did a little more footwork on this one to narrow it down.  It only happens with the Vivecraft Forge profile,  If I load up regular Vivecraft, it works as expected.

But whenever I change /gamemode creative, it immediately crashes Minecraft if I try to open inventory.

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.hasSearchBar()Z

https://pastebin.com/jDQBCUpT

**Comment by Techjar** [comment]
This was already fixed, update to the latest 1.11.2 release (9r3 as of writing this).
