### ISSUE TITLE
Error when trying to run .exe (hs_err_pid8300.log)

### ISSUE THREAD

**Issue by Bind777** [jrbudda/Vivecraft_111#53]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffed49afd0c, pid=8300, tid=0x0000000000002110
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [d3d9.dll+0xfd0c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x000000001f413000):  JavaThread "AWT-Windows" daemon [_thread_in_native, id=8464, stack(0x000000001fd80000,0x000000001fe80000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x000000001fe7dc60, RCX=0x00000000232be140, RDX=0x000000001fe7e470
RSP=0x000000001fe7dbb8, RBP=0x000000001fe7df50, RSI=0x0000000000000001, RDI=0x00000000232b6480
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x00000000232bef5c, R11=0x0000000000000246
R12=0x0000000000000001, R13=0x000000001fe7e470, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007ffed49afd0c, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000001fe7dbb8)
0x000000001fe7dbb8:   00007ffed49b167f 000000001fe7dc18
0x000000001fe7dbc8:   000000001fe7dc20 00000000000005f4
0x000000001fe7dbd8:   0000000000010001 0000000000000000
0x000000001fe7dbe8:   00000000232b6480 0000000000000000
0x000000001fe7dbf8:   00007ffed49c76a6 0000000000000000
0x000000001fe7dc08:   0000000000000000 0000000000000001
0x000000001fe7dc18:   0000000000000001 0000000000000000
0x000000001fe7dc28:   0000000000000000 0000000000005c88
0x000000001fe7dc38:   0000000000005c90 0000000000000000
0x000000001fe7dc48:   000000001fe7dc98 0000000000000000
0x000000001fe7dc58:   000000000000001a 0000000000000000
0x000000001fe7dc68:   0000000000000000 0000000023299f40
0x000000001fe7dc78:   00000000232be140 0000000000000000
0x000000001fe7dc88:   000000000075a4b8 0000000000000000
0x000000001fe7dc98:   0000000000000003 0000000000000000
0x000000001fe7dca8:   0000000000000000 0000000000000048 

Instructions: (pc=0x00007ffed49afd0c)
0x00007ffed49afcec:   e9 10 fe ff ff cc cc cc cc cc cc cc cc cc cc cc
0x00007ffed49afcfc:   cc cc cc cc ff 25 00 00 00 00 c0 96 01 80 01 00
0x00007ffed49afd0c:   00 00 5c 24 20 55 56 57 41 54 41 55 41 56 41 57
0x00007ffed49afd1c:   48 8d 6c 24 c0 48 81 ec 40 01 00 00 48 8b 05 a9 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000001fe7dc60 is pointing into the stack for thread: 0x000000001f413000
RCX=0x00000000232be140 is an unknown value
RDX=0x000000001fe7e470 is pointing into the stack for thread: 0x000000001f413000
RSP=0x000000001fe7dbb8 is pointing into the stack for thread: 0x000000001f413000
RBP=0x000000001fe7df50 is pointing into the stack for thread: 0x000000001f413000
RSI=0x0000000000000001 is an unknown value
RDI=0x00000000232b6480 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x00000000232bef5c is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000000000000001 is an unknown value
R13=0x000000001fe7e470 is pointing into the stack for thread: 0x000000001f413000
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x000000001fd80000,0x000000001fe80000],  sp=0x000000001fe7dbb8,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [d3d9.dll+0xfd0c]
C  [d3d9.dll+0x1167f]
C  [d3d9.dll+0x276a6]
C  [d3d9.dll+0x2cb68]
C  [d3d9.dll+0x2a81e]
C  [awt.dll+0x19e2d]
C  [awt.dll+0x19f8b]
C  [awt.dll+0x1a93f]
C  [awt.dll+0x1e4c5]
C  [awt.dll+0x1b609]
C  0x0000000002807f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.java2d.d3d.D3DGraphicsDevice.getDeviceCapsNative(I)I+0
j  sun.java2d.d3d.D3DGraphicsDevice.access$000(I)I+1
j  sun.java2d.d3d.D3DGraphicsDevice$1.run()V+8
v  ~StubRoutines::call_stub
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00000000026f0800 JavaThread "DestroyJavaVM" [_thread_blocked, id=8320, stack(0x00000000025f0000,0x00000000026f0000)]
  0x000000001f423800 JavaThread "AWT-EventQueue-0" [_thread_in_native, id=8424, stack(0x0000000021300000,0x0000000021400000)]
=>0x000000001f413000 JavaThread "AWT-Windows" daemon [_thread_in_native, id=8464, stack(0x000000001fd80000,0x000000001fe80000)]
  0x000000001f410800 JavaThread "AWT-Shutdown" [_thread_blocked, id=8284, stack(0x000000001fc80000,0x000000001fd80000)]
  0x000000001f40f800 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=8416, stack(0x000000001fb80000,0x000000001fc80000)]
  0x000000001e25c800 JavaThread "Service Thread" daemon [_thread_blocked, id=8396, stack(0x000000001ed80000,0x000000001ee80000)]
  0x000000001e1d0000 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=8392, stack(0x000000001ec80000,0x000000001ed80000)]
  0x000000001e1c1000 JavaThread "C2 CompilerThread2" daemon [_thread_blocked, id=8376, stack(0x000000001eb80000,0x000000001ec80000)]
  0x000000001e1be000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=8372, stack(0x000000001ea80000,0x000000001eb80000)]
  0x000000001e1ba800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=8368, stack(0x000000001e980000,0x000000001ea80000)]
  0x000000001e1b9000 JavaThread "Attach Listener" daemon [_thread_blocked, id=8364, stack(0x000000001e880000,0x000000001e980000)]
  0x000000001e1b6800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=8360, stack(0x000000001e780000,0x000000001e880000)]
  0x000000001e1b0800 JavaThread "Finalizer" daemon [_thread_blocked, id=8356, stack(0x000000001e590000,0x000000001e690000)]
  0x00000000027e6000 JavaThread "Reference Handler" daemon [_thread_blocked, id=8352, stack(0x000000001e090000,0x000000001e190000)]

Other Threads:
  0x000000001c2a9000 VMThread [stack: 0x000000001df90000,0x000000001e090000] [id=8348]
  0x000000001e28a000 WatcherThread [stack: 0x000000001ee80000,0x000000001ef80000] [id=8620]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 76288K, used 9950K [0x000000076b100000, 0x0000000770600000, 0x00000007c0000000)
  eden space 65536K, 15% used [0x000000076b100000,0x000000076bab7b38,0x000000076f100000)
  from space 10752K, 0% used [0x000000076fb80000,0x000000076fb80000,0x0000000770600000)
  to   space 10752K, 0% used [0x000000076f100000,0x000000076f100000,0x000000076fb80000)
 ParOldGen       total 175104K, used 0K [0x00000006c1200000, 0x00000006cbd00000, 0x000000076b100000)
  object space 175104K, 0% used [0x00000006c1200000,0x00000006c1200000,0x00000006cbd00000)
 Metaspace       used 10794K, capacity 10980K, committed 11008K, reserved 1058816K
  class space    used 1442K, capacity 1528K, committed 1536K, reserved 1048576K

Card table byte_map: [0x0000000011bb0000,0x00000000123b0000] byte_map_base: 0x000000000e5a7000

Marking Bits: (ParMarkBitMap*) 0x000000005f76c720
 Begin Bits: [0x0000000013100000, 0x00000000170b8000)
 End Bits:   [0x00000000170b8000, 0x000000001b070000)

Polling page: 0x0000000002470000

CodeCache: size=245760Kb used=2035Kb max_used=2035Kb free=243724Kb
 bounds [0x00000000027f0000, 0x0000000002a60000, 0x00000000117f0000]
 total_blobs=914 nmethods=449 adapters=378
 compilation: enabled

Compilation events (10 events):
Event: 0.219 Thread 0x000000001e1d0000  444       3       java.util.ArrayList$Itr::hasNext (20 bytes)
Event: 0.220 Thread 0x000000001e1d0000 nmethod 444 0x00000000029ec6d0 code [0x00000000029ec820, 0x00000000029ec9f0]
Event: 0.220 Thread 0x000000001e1d0000  446       1       javax.swing.text.GapVector::getGapEnd (5 bytes)
Event: 0.220 Thread 0x000000001e1d0000 nmethod 446 0x00000000029eca90 code [0x00000000029ecbe0, 0x00000000029eccf0]
Event: 0.220 Thread 0x000000001e1d0000  447       1       javax.swing.text.GapVector::getGapStart (5 bytes)
Event: 0.220 Thread 0x000000001e1d0000 nmethod 447 0x00000000029ecd50 code [0x00000000029ecea0, 0x00000000029ecfb0]
Event: 0.220 Thread 0x000000001e1d0000  448       1       javax.swing.text.GapVector::getArray (5 bytes)
Event: 0.220 Thread 0x000000001e1d0000 nmethod 448 0x00000000029ed010 code [0x00000000029ed160, 0x00000000029ed270]
Event: 0.232 Thread 0x000000001e1d0000  449       3       java.util.HashMap::<init> (11 bytes)
Event: 0.232 Thread 0x000000001e1d0000 nmethod 449 0x00000000029ed2d0 code [0x00000000029ed440, 0x00000000029ed650]

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Internal exceptions (10 events):
Event: 0.016 Thread 0x00000000026f0800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x000000076b107ca8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\
Event: 0.016 Thread 0x00000000026f0800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x000000076b107f90) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims
Event: 0.051 Thread 0x00000000026f0800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b1a7890) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.051 Thread 0x00000000026f0800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b1a7aa0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.051 Thread 0x00000000026f0800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b1ab710) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.051 Thread 0x00000000026f0800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b1ab920) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.053 Thread 0x00000000026f0800 Exception <a 'java/io/FileNotFoundException'> (0x000000076b1adcd8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.070 Thread 0x00000000026f0800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076b3c3e78) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.071 Thread 0x00000000026f0800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076b3d1248) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.108 Thread 0x00000000026f0800 Exception <a 'java/io/FileNotFoundException'> (0x000000076b482aa8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 0.232 loading class sun/java2d/pipe/RenderQueue done
Event: 0.232 loading class sun/java2d/d3d/D3DRenderQueue done
Event: 0.232 loading class sun/java2d/pipe/RenderBuffer
Event: 0.232 loading class sun/java2d/pipe/RenderBuffer done
Event: 0.232 loading class sun/java2d/d3d/D3DRenderQueue$1
Event: 0.232 loading class sun/java2d/d3d/D3DRenderQueue$1 done
Event: 0.232 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result
Event: 0.232 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result done
Event: 0.232 loading class sun/java2d/d3d/D3DGraphicsDevice$1
Event: 0.232 loading class sun/java2d/d3d/D3DGraphicsDevice$1 done

Dynamic libraries:
0x00007ff794db0000 - 0x00007ff794de7000 	C:\Program Files\Java\jre1.8.0_131\bin\javaw.exe
0x00007ffefc410000 - 0x00007ffefc5eb000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffefa470000 - 0x00007ffefa51e000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffef93e0000 - 0x00007ffef9629000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffefc350000 - 0x00007ffefc3f1000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffef9c80000 - 0x00007ffef9d1d000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffefa520000 - 0x00007ffefa579000 	C:\WINDOWS\System32\sechost.dll
0x00007ffefa5f0000 - 0x00007ffefa715000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffefaae0000 - 0x00007ffefac2a000 	C:\WINDOWS\System32\USER32.dll
0x00007ffef8930000 - 0x00007ffef894e000 	C:\WINDOWS\System32\win32u.dll
0x00007ffefa440000 - 0x00007ffefa467000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffef9790000 - 0x00007ffef9919000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffef9100000 - 0x00007ffef919a000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffef9690000 - 0x00007ffef9786000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffeefb60000 - 0x00007ffeefdc7000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_108e4f62dfe5d999\COMCTL32.dll
0x00007ffef9970000 - 0x00007ffef9c69000 	C:\WINDOWS\System32\combase.dll
0x00007ffef91a0000 - 0x00007ffef920a000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffeface0000 - 0x00007ffefad0d000 	C:\WINDOWS\System32\IMM32.DLL
0x000000005f7f0000 - 0x000000005f8c2000 	C:\Program Files\Java\jre1.8.0_131\bin\msvcr100.dll
0x000000005ef50000 - 0x000000005f7ec000 	C:\Program Files\Java\jre1.8.0_131\bin\server\jvm.dll
0x00007ffef9c70000 - 0x00007ffef9c78000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffeea500000 - 0x00007ffeea509000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffef6cb0000 - 0x00007ffef6cd3000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffeebc20000 - 0x00007ffeebc2a000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffefa580000 - 0x00007ffefa5ec000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffef6a30000 - 0x00007ffef6a5b000 	C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffef9920000 - 0x00007ffef9969000 	C:\WINDOWS\System32\cfgmgr32.dll
0x000000005ef40000 - 0x000000005ef4f000 	C:\Program Files\Java\jre1.8.0_131\bin\verify.dll
0x000000005ef10000 - 0x000000005ef39000 	C:\Program Files\Java\jre1.8.0_131\bin\java.dll
0x000000005eef0000 - 0x000000005ef06000 	C:\Program Files\Java\jre1.8.0_131\bin\zip.dll
0x00007ffefad10000 - 0x00007ffefc147000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffefa160000 - 0x00007ffefa20a000 	C:\WINDOWS\System32\shcore.dll
0x00007ffef8a00000 - 0x00007ffef90f2000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffefa3e0000 - 0x00007ffefa431000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffef8880000 - 0x00007ffef8891000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffef88e0000 - 0x00007ffef892c000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffef88c0000 - 0x00007ffef88d5000 	C:\WINDOWS\System32\profapi.dll
0x000000005ed50000 - 0x000000005eee8000 	C:\Program Files\Java\jre1.8.0_131\bin\awt.dll
0x00007ffefa9c0000 - 0x00007ffefaa7f000 	C:\WINDOWS\System32\OLEAUT32.dll
0x00007ffef6dd0000 - 0x00007ffef6e4e000 	C:\WINDOWS\SYSTEM32\apphelp.dll
0x00007ffef6f90000 - 0x00007ffef7025000 	C:\WINDOWS\system32\uxtheme.dll
0x00007ffefa720000 - 0x00007ffefa886000 	C:\WINDOWS\System32\MSCTF.dll
0x0000000180000000 - 0x0000000180043000 	C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
0x00000000613e0000 - 0x0000000061483000 	C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_08e667efa83ba076\MSVCR90.dll
0x00007ffef5480000 - 0x00007ffef54aa000 	C:\WINDOWS\system32\dwmapi.dll
0x00007ffefa210000 - 0x00007ffefa355000 	C:\WINDOWS\System32\ole32.dll
0x000000005ed00000 - 0x000000005ed47000 	C:\Program Files\Java\jre1.8.0_131\bin\fontmanager.dll
0x000000005ece0000 - 0x000000005ecfa000 	C:\Program Files\Java\jre1.8.0_131\bin\net.dll
0x00007ffef8190000 - 0x00007ffef81ec000 	C:\WINDOWS\system32\mswsock.dll
0x000000005ecc0000 - 0x000000005ecd1000 	C:\Program Files\Java\jre1.8.0_131\bin\nio.dll
0x00007ffef8330000 - 0x00007ffef8347000 	C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffef7db0000 - 0x00007ffef7de4000 	C:\WINDOWS\system32\rsaenh.dll
0x00007ffef8440000 - 0x00007ffef8465000 	C:\WINDOWS\SYSTEM32\bcrypt.dll
0x00007ffef87b0000 - 0x00007ffef87d9000 	C:\WINDOWS\SYSTEM32\USERENV.dll
0x00007ffef8350000 - 0x00007ffef835b000 	C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x00007ffef7f30000 - 0x00007ffef7f67000 	C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffefc400000 - 0x00007ffefc408000 	C:\WINDOWS\System32\NSI.dll
0x00007ffef48f0000 - 0x00007ffef4906000 	C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
0x00007ffef4c40000 - 0x00007ffef4c5a000 	C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x00007ffec6920000 - 0x00007ffec6a41000 	C:\WINDOWS\system32\opengl32.dll
0x00007ffed75f0000 - 0x00007ffed761c000 	C:\WINDOWS\SYSTEM32\GLU32.dll
0x00007ffed49a0000 - 0x00007ffed4b29000 	C:\WINDOWS\system32\d3d9.dll
0x00007ffed39e0000 - 0x00007ffed3abf000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_a2b0acab06663645\nvldumdx.dll
0x00007ffef9210000 - 0x00007ffef93d9000 	C:\WINDOWS\System32\crypt32.dll
0x00007ffef88a0000 - 0x00007ffef88b1000 	C:\WINDOWS\System32\MSASN1.dll
0x00007ffef9630000 - 0x00007ffef9686000 	C:\WINDOWS\System32\WINTRUST.DLL
0x00007ffefa9a0000 - 0x00007ffefa9bd000 	C:\WINDOWS\System32\imagehlp.dll
0x00007ffec39a0000 - 0x00007ffec49b5000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_a2b0acab06663645\nvd3dumx.dll
0x00007ffee9f40000 - 0x00007ffeea0e9000 	C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
java_command: G:\Chrome Downloads\vivecraft-1.11.2-jrbudda-9r3-installer.exe
java_class_path (initial): G:\Chrome Downloads\vivecraft-1.11.2-jrbudda-9r3-installer.exe
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=C:\ProgramData\Oracle\Java\javapath;c:\program files\oculus\support\oculus-runtime;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\fiska\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Java\jre1.8.0_131\bin
USERNAME=fiska
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 15063 (10.0.15063.296)

CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 94 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 16698916k(14145860k free), swap 19189284k(15815168k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.131-b11) for windows-amd64 JRE (1.8.0_131-b11), built on Mar 15 2017 01:23:53 by "java_re" with MS VC++ 10.0 (VS2010)

time: Sun May 21 20:31:44 2017
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by jrbudda** [comment]
looks like this https://bugs.openjdk.java.net/browse/JDK-8178537 not really a vivecraft issue

**Comment by Bind777** [comment]
Thanks for the extremely prompt reply. I'm terrible at reading error logs and I assumed it was vivecraft related because the standard Minecraft client worked. Seems to be related to rivatuner. I will try again without it running.

**Comment by Bind777** [comment]
Got it to work by disbaling MSI Afterburner and RIvatuner.

Thanks again JR
