### ISSUE TITLE
Java platform SE binary has stopped working

### ISSUE THREAD

**Issue by Polaris12** [jrbudda/Vivecraft_111#56]
i got my vive headset and i followed many tutorials and threads on how to install this mod, my minecraft log as i launch the game shoots out a lot of errors. and ends with a message "Java platform SE binary has stopped working" it failed to launch right before the menu would show up (just in case that could mean anything)

**Comment by Techjar** [comment]
Update your nvidia drivers.

**Comment by Polaris12** [comment]
seems to be the issue thanks for your help :)

**Comment by Techjar** [comment]
You're welcome. If you're wondering why it was broken, specifically the 378.49 driver version broke Vivecraft (and some other stuff) for some reason. It was a big issue back when that release happened, we had to tell people to downgrade their drivers.
