### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by dustygingercat** [jrbudda/Vivecraft_111#57]
When i launch vivecraft on 1.12 it loads and loads and loads then goes black and turns off and brings me back to a page that says game crash it looks like your running an supported version of the game then this messenge The game crashed whilst tesselating block model
The game crashed whilst tesselating block model
Error: java.lang.NullPointerException: Tesselating block model Can you help me?

**Comment by Techjar** [comment]
Please supply the full crash report from .minecraft/crash-reports

**Comment by OMG-Crackers** [comment]
I have like 50ish mods and i start it it all loads through forge but as soon as it opens the game it self it goes white and flickers then crashes?

any ideas?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.11.2-5.2.2.jar)
  IC2core (industrialcraft-2-2.7.74-ex111.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.7.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 7/21/17 10:54 PM
Description: Unexpected error

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/chunk/RenderChunk.func_178581_b(FFFLnet/minecraft/client/renderer/chunk/ChunkCompileTaskGenerator;)V @539: aload
  Reason:
    Type integer (current frame, locals[22]) is not assignable to reference type
  Current Frame:
    bci: @539
    flags: { }
    locals: { 'net/minecraft/client/renderer/chunk/RenderChunk', float, float, float, 'net/minecraft/client/renderer/chunk/ChunkCompileTaskGenerator', 'net/minecraft/client/renderer/chunk/CompiledChunk', integer, 'net/minecraft/util/math/BlockPos', 'net/minecraft/util/math/BlockPos', 'net/minecraft/client/renderer/chunk/VisGraph', 'java/util/HashSet', 'ChunkCacheOF', '[Z', 'net/minecraft/client/renderer/BlockRendererDispatcher', integer, integer, 'java/util/Iterator', 'java/lang/Object', 'BlockPosM', 'net/minecraft/block/state/IBlockState', 'net/minecraft/block/Block', '[Lnet/minecraft/util/BlockRenderLayer;', integer, 'net/minecraft/util/BlockRenderLayer', integer, 'net/minecraft/client/renderer/VertexBuffer', 'RenderEnv' }
    stack: { '[Z', integer, integer, 'net/minecraft/client/renderer/BlockRendererDispatcher', 'net/minecraft/block/state/IBlockState', 'BlockPosM', 'ChunkCacheOF', 'net/minecraft/client/renderer/VertexBuffer' }
  Bytecode:
    0x0000000: bb00 4959 b701 1e3a 0504 3606 2ab4 0078
    0x0000010: 3a07 1907 100f 100f 100f b601 223a 0819
    0x0000020: 04b6 0126 b601 2919 04b6 012d b201 31a5
    0x0000030: 000c 1904 b601 26b6 0134 b119 0419 05b6
    0x0000040: 0138 1904 b601 26b6 0134 a700 103a 0919
    0x0000050: 04b6 0126 b601 3419 09bf bb01 3c59 b701
    0x0000060: 3d3a 09b8 005b 3a0a 2ab4 009b c602 c42a
    0x0000070: b701 413a 0b19 0bb6 0146 9a02 49b2 0148
    0x0000080: 0460 b301 4819 0bb6 014b b201 4dbe bc04
    0x0000090: 3a0c b801 53b6 0157 3a0d b201 5bb6 015e
    0x00000a0: 360e b201 61b6 015e 360f 1907 1908 b801
    0x00000b0: 67b9 016d 0100 3a10 1910 b901 7801 0099
    0x00000c0: 019a 1910 b901 7c01 003a 1119 11c0 0163
    0x00000d0: 3a12 190b 1912 b601 803a 1319 13b9 0186
    0x00000e0: 0100 3a14 1913 b901 8901 0099 000a 1909
    0x00000f0: 1912 b601 8d19 13b8 0195 9900 3f19 0b19
    0x0000100: 12b2 0199 b601 9d3a 1519 15c6 002e b201
    0x0000110: a319 15b6 01a7 3a16 1916 c600 1f19 1619
    0x0000120: 15b6 01ad 9900 0e19 0a19 15b6 01b1 57a7
    0x0000130: 000a 1905 1915 b601 b715 0e99 000b b201
    0x0000140: 4d3a 15a7 0012 2ab4 007c 3a15 1915 0319
    0x0000150: 14b6 01bb 5303 3616 1516 1915 bea2 00e6
    0x0000160: 1915 1516 323a 1715 0e99 0023 1914 b201
    0x0000170: 5b05 bd00 0459 0319 1353 5904 1917 53b8
    0x0000180: 01c0 3618 1518 9a00 06a7 00b4 150f 9900
    0x0000190: 12b2 0161 04bd 0004 5903 1917 53b8 01c4
    0x00001a0: 2ab4 0094 9900 0d2a 1914 1917 b701 c73a
    0x00001b0: 1719 17b6 01c8 3618 1914 b601 ccb9 01d0
    0x00001c0: 0100 b201 d6a5 0078 1904 b601 0515 18b6
    0x00001d0: 01da 3a19 1919 1917 b601 de19 1919 0b19
    0x00001e0: 1319 12b6 01e2 3a1a 191a 1904 b601 05b6
    0x00001f0: 01e8 1905 1917 b601 eb9a 0012 1905 1917
    0x0000200: b601 ee2a 1919 1907 b601 0f19 0c15 185c
    0x0000210: 3319 0d19 1319 1219 0b19 1919 16b8 01f4
    0x0000220: 8054 191a b601 f799 0016 2a19 04b6 0105
    0x0000230: 1905 190c b701 fb19 1a03 b601 ff84 1601
    0x0000240: a7ff 1815 0f99 0011 b201 6104 bd00 0459
    0x0000250: 0301 53b8 01c4 a7fe 62b2 014d 3a10 1910
    0x0000260: be36 1103 3612 1512 1511 a200 5419 1015
    0x0000270: 1232 3a13 190c 1913 b601 c833 9900 0a19
    0x0000280: 0519 13b6 0202 1905 1913 b601 eb99 002b
    0x0000290: b802 0599 0010 1904 b601 0519 13b6 010b
    0x00002a0: b802 0b2a 1913 2324 2519 04b6 0105 1913
    0x00002b0: b601 0b19 05b6 0117 8412 01a7 ffab 190b
    0x00002c0: b602 0e19 0519 09b6 0212 b602 162a b400
    0x00002d0: 53b6 0129 190a b802 193a 0c2a b400 5db8
    0x00002e0: 0219 3a0d 190c 2ab4 005d b902 1f02 0057
    0x00002f0: 190d 190a b902 1f02 0057 2ab4 005d b902
    0x0000300: 2201 002a b400 5d19 0ab9 0225 0200 572a
    0x0000310: b400 9d19 0d19 0cb6 0229 2ab4 0053 b601
    0x0000320: 34a7 000f 3a1b 2ab4 0053 b601 3419 1bbf
    0x0000330: b1                                     
  Exception Handler Table:
    bci [39, 50] => handler: 77
    bci [59, 66] => handler: 77
    bci [77, 79] => handler: 77
    bci [724, 794] => handler: 804
    bci [804, 806] => handler: 804
  Stackmap Table:
    full_frame(@59,{Object[#2],Float,Float,Float,Object[#18],Object[#73],Integer,Object[#9],Object[#9]},{})
    same_locals_1_stack_item_frame(@77,Object[#314])
    same_frame(@90)
    full_frame(@184,{Object[#2],Float,Float,Float,Object[#18],Object[#73],Integer,Object[#9],Object[#9],Object[#316],Object[#367],Object[#323],Object[#369],Object[#371],Integer,Integer,Object[#373]},{})
    full_frame(@245,{Object[#2],Float,Float,Float,Object[#18],Object[#73],Integer,Object[#9],Object[#9],Object[#316],Object[#367],Object[#323],Object[#369],Object[#371],Integer,Integer,Object[#373],Object[#4],Object[#355],Object[#386],Object[#399]},{})
    append_frame(@306,Object[#435],Object[#425])
    chop_frame(@313,2)
    same_frame(@326)
    append_frame(@341,Object[#444])
    append_frame(@344,Integer)
    append_frame(@396,Object[#103])
    same_frame(@416)
    same_frame(@433)
    append_frame(@523,Integer,Object[#14],Object[#484])
    full_frame(@573,{Object[#2],Float,Float,Float,Object[#18],Object[#73],Integer,Object[#9],Object[#9],Object[#316],Object[#367],Object[#323],Object[#369],Object[#371],Integer,Integer,Object[#373],Object[#4],Object[#355],Object[#386],Object[#399],Object[#444],Integer},{})
    chop_frame(@579,1)
    full_frame(@598,{Object[#2],Float,Float,Float,Object[#18],Object[#73],Integer,Object[#9],Object[#9],Object[#316],Object[#367],Object[#323],Object[#369],Object[#371],Integer,Integer,Object[#373]},{})
    chop_frame(@601,1)
    append_frame(@614,Object[#444],Integer,Integer)
    append_frame(@646,Object[#103])
    same_frame(@675)
    chop_frame(@696,1)
    chop_frame(@702,3)
    full_frame(@707,{Object[#2],Float,Float,Float,Object[#18],Object[#73],Integer,Object[#9],Object[#9],Object[#316],Object[#367],Object[#323]},{})
    same_locals_1_stack_item_extended(@804,Object[#314])
    chop_frame(@816,1)

	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1774)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:674)
	at net.minecraft.client.main.Main.main(Main.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1020036112 bytes (972 MB) / 4024958976 bytes (3838 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2388 Optifine OptiFine_1.11.2_HD_U_C3 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2388.jar) 
	UCHIJA	forge{13.20.1.2388} [Minecraft Forge] (forge-1.11.2-13.20.1.2388.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	movillages{1.5.3} [Mo' Villages] ([1.11]MoVillages-1.5.3.jar) 
	UCHIJA	bettercombatmod{1.4.0} [Better Combat] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJA	examplemod{1.0} [examplemod] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJA	betterfoliage{2.1.7} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.7.jar) 
	UCHIJA	biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar) 
	UCHIJA	biomesyougo{5.2.0} [BiomesYouGo] (BiomesYouGo (Version 5.2.0).jar) 
	UCHIJA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJA	chiselsandbits{13.11} [Chisels & Bits] (chiselsandbits-13.11.jar) 
	UCHIJA	coralreef{1.0} [Coral Reef] (CoralReef-1.4.jar) 
	UCHIJA	crystalcaves{1.0} [Crystal Caves] (CrystalCaves-1.0.jar) 
	UCHIJA	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2(21jul17).jar) 
	UCHIJA	dynamiclights{1.4.6} [Dynamic Lights] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_onfire{1.0.7} [Dynamic Lights on burning] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_creepers{1.0.6} [Dynamic Lights on Creepers] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_dropitems{1.1.0} [Dynamic Lights on ItemEntities] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_entityclasses{1.0.1} [Dynamic Lights on specified Entities] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_mobequipment{1.1.0} [Dynamic Lights on Mob Equipment] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_flamearrows{1.0.1} [Dynamic Lights on Flame enchanted Arrows] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_floodlights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_otherplayers{1.0.9} [Dynamic Lights Other Player Light] (DynamicLights-1.11.2.jar) 
	UCHIJA	dynamiclights_theplayer{1.1.3} [Dynamic Lights Player Light] (DynamicLights-1.11.2.jar) 
	UCHIJA	extrabitmanipulation{1.11.2-3.0.6} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.6.jar) 
	UCHIJA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJA	gravestone{1.0.10} [Gravestone] (GraveStone-1.11.2-Graves-1.0.10.jar) 
	UCHIJA	hgp{Release} [Horizontal Glass Panes] (hgp-1.11.2-1.1.4.jar) 
	UCHIJA	hopperducts{1.4.9.2} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.2.jar) 
	UCHIJA	ic2{2.7.74-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.74-ex111.jar) 
	UCHIJA	levelup{${version}} [Level Up!] (LevelUp!-0.14.5-1.11.2.jar) 
	UCHIJA	malisiscore{1.11.2-5.2.2} [MalisisCore] (malisiscore-1.11.2-5.2.2.jar) 
	UCHIJA	malisisdoors{1.11.2-6.1.2} [MalisisDoors] (malisisdoors-1.11.2-6.1.2.jar) 
	UCHIJA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJA	minecolonies{1.11.2-0.8.3185} [MineColonies] (minecolonies-universal-1.11.2-0.8.3185.jar) 
	UCHIJA	ms{v1.84} [Mo' Shiz Mod] (Mo' Shiz v1.84.jar) 
	UCHIJA	mobends{0.23.5} [Mo'Bends] (mobends-0.23.5_for_MC-1.11.2.jar) 
	UCHIJA	natura{1.11.2-4.2.0.24} [Natura] (natura-1.11.2-4.2.0.24.jar) 
	UCHIJA	nex{1.1.8.9} [NetherEx] (NetherEx-1.11.2-1.1.8.9.jar) 
	UCHIJA	samsocean{1.0.1} [Ocean Floor Classic] (OceanFloor-1.11-1.0.1.jar) 
	UCHIJA	shipmod{1.0} [The ship mod] (ShipMod-1.1.jar) 
	UCHIJA	simplecorn{2.2.0} [Simple Corn] (simpleCorn1.11.2-2.2.0.jar) 
	UCHIJA	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCHIJA	toroquest{1.11.2-4.0} [ToroQuest] (toroquest-1.11.2-4.0.jar) 
	UCHIJA	uncharted{v03} [Uncharted] (Uncharted_1.11.2_v03.jar) 
	UCHIJA	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.11-1.0.v.19.jar) 
	UCHIJA	wearablebackpacks{2.5.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.5.0.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.11.2-5.2.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
IC2core (industrialcraft-2-2.7.74-ex111.jar)
  
DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.7.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.162.4' Renderer: 'Radeon (TM) RX 480 Graphics'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: vivecraft-1.11.2-jrbudda-12-forge
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.5.13474 Compatibility Profile Context 22.19.162.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft,fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 8
	Antialiasing: 0
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.162.4
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by jrbudda** [comment]
its almost certainly one of these 
MalisisCorePlugin (malisiscore-1.11.2-5.2.2.jar)
IC2core (industrialcraft-2-2.7.74-ex111.jar)
DLFMLCorePlugin (DynamicLights-1.11.2.jar)
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.7.jar)

if you can figure out which we can look into it deeper

**Comment by OMG-Crackers** [comment]
ok well it worked without vivcraft installed same forge version and everything so ill try to pin point it top see if you guys could fix it or the modder who created it.

**Comment by OMG-Crackers** [comment]
ok it was BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.7.jar) im guessing its messing with the same class or file as vivecraft lol

**Comment by OMG-Crackers** [comment]
first try too lol

**Comment by OMG-Crackers** [comment]
Thank you :-)

**Comment by jrbudda** [comment]
this should fix it.

[vivecraft-1.11.2-jrbudda-12r1-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/1167344/vivecraft-1.11.2-jrbudda-12r1-installer.exe.zip)

**Comment by inviktus** [comment]
Heyas
I'm having this issue also, using vivecraft-12r6 mc 1.10.2 with FTB Beyond version something. 
I do not get the crash without vivecraft. The game will run for a bit and then become unresponsive, when I close it, it gives the tesselation on block error msg

My crashlog can be found here [https://drive.google.com/open?id=0BwbXP42d2ORmWjZEVDJTYVpmZG8](url)

many diamonds in advance for you ^_^

**Comment by Techjar** [comment]
@inviktus Looks like a null TileEntity, I haven't a clue how Vivecraft would cause such a thing. Could you open a new issue for this? It's not really related to this one, and this one is over 2 months old.

**Comment by inviktus** [comment]
sure thing!
