### ISSUE TITLE
Witches causing crashing

### ISSUE THREAD

**Issue by inviktus** [jrbudda/Vivecraft_111#58]
I'm running vivecraft 1.12 with forge and a shader pack, each time I see a witch, my game will crash.
The launcher will display an error "game has crashed unexpectedly, we are sorry for the inconvenience"

My work around is to launch regular ole minecraft, kill the witch, then save and exit, relaunch the game and continue playing in vr.  :(

I don't know how to be of any more use in diagnosing this issue as I am a total noob, but I am good at following instructions! :)
![image](https://user-images.githubusercontent.com/1152944/28246614-d3af8b84-6a50-11e7-8eba-6871c0f7a362.png)

**Comment by jrbudda** [comment]
Must be a new spell they gave witches in 1.12

**Comment by inviktus** [comment]
@jrbudda also just want to say thank you for your work in creating vivecraft.. it's one of the best experiences I've had with my vive so far :) <3

**Comment by jrbudda** [comment]
hmm cannot reproduce your issue. Please grab the fml-latest.log from your minecraft/logs directory and drag it here.

**Comment by inviktus** [comment]
Right away Sir!

[logs.zip](https://github.com/jrbudda/Vivecraft_111/files/1150952/logs.zip)

**Comment by jrbudda** [comment]
oh get rid of shadersmod, it's already built into vivecraft.

**Comment by inviktus** [comment]
ohh
ok thanks! :)

**Comment by jrbudda** [comment]
Also this log appears to be a 'game crashed on loading' not a 'i saw a witch and it crashed'

**Comment by inviktus** [comment]
I have had that happen twice, if I try to load vivecraft with forge it does that.
otherwise, I can load the vivecraft 1.12 on its own and play until I see a witch

**Comment by jrbudda** [comment]
ya well if you load without forge it wont try to load the shadersmod mod jar

**Comment by inviktus** [comment]
That makes a lot of sense. I will try to find a witch now that I've removed shadersmod.jar and see if the problem is still there.

Thanks for your help!

**Comment by jrbudda** [comment]
you can spawn witches with eggs in creative

**Comment by inviktus** [comment]
Spawned in a witch.. no crash. switched to survival (witch notices me) and within 2 seconds, game crashed..

**Comment by inviktus** [comment]
I think I just crashed it trying to ride a pig.. :<

**Comment by jrbudda** [comment]
should fix

[vivecraft-1.12-jrbudda-1r2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/1151224/vivecraft-1.12-jrbudda-1r2-installer.exe.zip)

**Comment by inviktus** [comment]
I will run it this evening after work and let you know! Cheers @jrbudda.

**Comment by inviktus** [comment]
oops wrong button.

**Comment by inviktus** [comment]
That seems to have done the trick!
And the crash on pig was actually another witch that crept up on me. Saw it when I logged in to test your patch.. no crashing!

I'm gonna drop you a donate for your effort :)
