### ISSUE TITLE
Hangs due to Tesselating block in world error

### ISSUE THREAD

**Issue by inviktus** [jrbudda/Vivecraft_111#59]
Heyas
I'm having this "tesselating block in world" issue, using vivecraft-12r6 mc 1.10.2 with FTB Beyond version something.
I do not get the crash without vivecraft. The game will run for a bit and then become unresponsive, when I close it, it gives the tesselation on block error msg

My crashlog can be found here https://drive.google.com/open?id=0BwbXP42d2ORmWjZEVDJTYVpmZG8

many diamonds in advance for you ^_^

**Comment by Techjar** [comment]
Looks like a null TileEntity, I haven't a clue how Vivecraft would cause such a thing. You're sure this is only with Vivecraft?

**Comment by inviktus** [comment]
positive. I've played this same modpack minus vivecraft without issue, for hours, just today. 
Minutes after loading it up in vivecraft to check out my build in vr (and combat sedentary lethargy) I saw this error.

**Comment by inviktus** [comment]
pardon if I am wrong, but isn't this the same/similar as the issue the other chap in the other thread was having?

**Comment by jrbudda** [comment]
malisiscore and codechickencore maybe having a ASM failure in one of them? Would need to see the startup fml-client-latest.log

**Comment by inviktus** [comment]
[fml-client-latest.log](https://github.com/jrbudda/Vivecraft_111/files/1329535/fml-client-latest.log)
Hope it helps :)

**Comment by jrbudda** [comment]
This does not appear to be a startup of Vivecraft

**Comment by inviktus** [comment]
Apologies, where might I find the startup vivecraft log? I'm not very familiar with this.

**Comment by jrbudda** [comment]
Its that file, but right after you start up with Vivecraft

**Comment by inviktus** [comment]
[fml-client-latest.log](https://github.com/jrbudda/Vivecraft_111/files/1330167/fml-client-latest.log)
hope thats it :)

**Comment by inviktus** [comment]
Did that file help at all?

**Comment by jrbudda** [comment]
Not really... the issue is something with malisisdoors, nothing in the log indicates what tho.

**Comment by inviktus** [comment]
Interesting. I've used a couple of doors from that mod.
Is there anything else I can do to help find out what causes this?

**Comment by jrbudda** [comment]
Does this still occur with updated malisiscore/doors on any Vivecraft version?

**Comment by Minerva-BOS** [comment]
I'm getting the same crash, but from what I'm seeing it seems to be related to cofhcore. What do you think?

[fml-client-latest.log](https://github.com/jrbudda/Vivecraft_111/files/1734652/fml-client-latest.log)
[crash-2018-02-18_20.24.08-client.txt](https://github.com/jrbudda/Vivecraft_111/files/1734653/crash-2018-02-18_20.24.08-client.txt)
