### ISSUE TITLE
Vivecraft crashing 

### ISSUE THREAD

**Issue by cmac007** [jrbudda/Vivecraft_111#6]
Please refer to my link on Reddit for crash report and comments. https://www.reddit.com/r/Vive/comments/5gcwu6/vivecraft_crash_error_log/

**Comment by jrbudda** [comment]
Looks like a openvr versioning issue. Have you tried deleting .minecraft and starting with a fresh install? (backup /saves)

**Comment by cmac007** [comment]
I tried that a couple times with both versions and still getting the same result

**Comment by jrbudda** [comment]
are you on the regular or beta steamVR branch?

**Comment by cmac007** [comment]
The regular

**Comment by jrbudda** [comment]
hmm could you pastebin your Game Output log on startup?
