### ISSUE TITLE
MP connectivity

### ISSUE THREAD

**Issue by tetsukuro21** [jrbudda/Vivecraft_111#61]
Users running Vivecraft following the instructions found in the FAQ "Using a third-party modpack launcher (FTB / Curse / Twitch / Technic, etc.)" appear to be unable to connect to my server. Server is running Tekkit 1.2.9g (MC 1.6.4). Server host is server.pro; is there a specific version of Vivecraft or Tekkit needed for this to work properly? They can connect normally without the plugin, and can play singleplayer with it, so I suspect the issue may be server-side. When trying to connect while having Vivecraft installed, the server shows "Can't resolve hostname".

**Comment by Espergium** [comment]
The oldest minecraft version supported is 1.7.10

**Comment by tetsukuro21** [comment]
Is there an older version of Vivecraft that worked for that version, or are we out of luck as far as Tekkit is concerned?

**Comment by Espergium** [comment]
Vivecraft was never made for 1.6.4. The oldest version it can run on is 1.7.10.

**Comment by tetsukuro21** [comment]
Gotcha - thanks for the quick response!

**Comment by tetsukuro21** [comment]
One thing I do find strange is that it works totally fine in singleplayer, using the 1.6.4 modpack. It just won't connect to servers.
