### ISSUE TITLE
"Legacy plugin does not specify API version" warning on server start

### ISSUE THREAD

**Issue by reverendjesus** [jrbudda/Vivecraft_111#62]
Just like it says in the title. It's my understanding this is simply a missing option in the YML.

**Comment by MasterNinad** [comment]
Yes, I also have the same issue -
![error](https://user-images.githubusercontent.com/89674431/148668442-0cf07e1d-00c6-450e-bc41-cc1c969f2335.png)

I am using aternos, with PaperMC 1.18.1

**Comment by Espergium** [comment]
SimplePrefix is not Vivecraft and this isn't an error. It's a general notice that doesn't hurt anyone. Ignore it.

**Comment by MasterNinad** [comment]
Ok
