### ISSUE TITLE
My locomotives aren't working. (Climbing, rowing a boat, jumping,ect)

### ISSUE THREAD

**Issue by QueenBay** [jrbudda/Vivecraft_111#7]
I can teleport but the other locomotives are not working.

**Comment by jrbudda** [comment]
just tested jump, sneak and climb in 1.11 all working. Do you maybe have them turned off in the options? Make sure 'simulate falling' is on if you're in TP mode.

**Comment by QueenBay** [comment]
Yes that worked. Thanks my dude.
