### ISSUE TITLE
Requires Java installation despite already installed

### ISSUE THREAD

**Issue by salzig** [jrbudda/Vivecraft_111#9]
Just got myself a new Computer running Windows 10. Installed Minecraft and lunched it once to make sure it works. 
Dowdloaded the current `vivecraft-1.11-jrbudda-3-installer.exe` and started it. 

Shows me a warning that Java 1.6 has to be installed. 

Tried to set a System wide Environment variables JAVA_HOME with `C:\Progra~2\Minecraft\runtime\jre-x64\1.8.0_25\` (checked that the value is correct by `cd %JAVA_HOME%` in cmd.exe). 
Installer still requires a Java Version to be installed. 

I would have expected it to recognise JAVA_HOME or even try the jre download by minecraft by it self.

**Comment by jrbudda** [comment]
is this one any different?

[vivecraft-1.11-jrbudda-3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/658218/vivecraft-1.11-jrbudda-3-installer.exe.zip)

**Comment by salzig** [comment]
Sadly not.

**Comment by jrbudda** [comment]
It's still asking for java 1.6? does it do any thing different if you rename the .exe to .jar and run it that way?

**Comment by salzig** [comment]
Yes, it's still asking for Java 1.6.

Renaming results in a main class not found.

**Comment by jrbudda** [comment]
I think you'll have to install java normally, something is up with the launch4j java search not finding it in the minecraft directory, I don't have control over that code.

**Comment by jrbudda** [comment]
I've also just learned you can open a command prompt and run `vivecraft-1.11-jrbudda-3.exe --l4j-debug` and it will make a launch4j.log file about where it is looking for the JRE and whatnot.

**Comment by salzig** [comment]
It is possible to use the minecraft provided JRE, but then you have to specify the exe as jar. 
```
C:\Progra~2\Minecraft\runtime\jre-x64\1.8.0_25\bin\java.exe -jar %userprofile%\Downloads\vivecraft-1.11-jrbudda-3-installer.exe
```

Anyways, thanks for your help!
